### ISSUE TITLE
multiple download backend support 

### ISSUE THREAD

**Issue by ipfans** [fiwippi/tanuki#1]
Now, tanuki only supports Mangadex as the download backend. Many more manga sites can be supported, and they can be added to the support list.

**Comment by lifeisperfecto** [comment]
Hey, this definitely sounds like a good idea. I'm a bit busy with coursework right now, hopefully sometime in April I could get round to this. It shouldn't be too difficult. 

Are there any specific sites you have in mind?

**Comment by ipfans** [comment]
For now, maybe some hentai site :P 

And some spec language site e.g. Chinese manga site.

**Comment by lifeisperfecto** [comment]
I'm looking at completely overhauling the downloading system so that it could work like a plugin-based system with multiple backends, I'll only get to it during the summer though. Keeping the issue open for now...

**Comment by lifeisperfecto** [comment]
So I've looked at implementing this and most websites don't offer an API let alone scraping, many are protected by Cloudflare and I don't want to go to all the effort to bypass that. I'll consider this feature but for now I don't think it will be added.
