### ISSUE TITLE
Optimize images with WebP format

### ISSUE THREAD

**Issue by ipfans** [fiwippi/tanuki#3]
[WebP](https://developers.google.com/speed/webp) is an image compression format, which can save the size of images significantly with the almost same image quality.

tanuki can provide image compression and format management feature to discount the size of existing manga to save more storage. Conversion can be done by extra tools like ImageMagick.

**Comment by lifeisperfecto** [comment]
Tanuki already decodes images with WebP.

Do you want the functionality to convert all images in a manga archive to WebP? I'm a bit hesitant to do this, I want to leave the original manga archive as untouched as possible, but mainly it's a lot of work for a feature I don't really want to implement. I'm not against doing this but right now this feature is very low on my priority list.

Closing for now...
