### ISSUE TITLE
ARM (Raspberry Pi) support?

### ISSUE THREAD

**Issue by OverlordAkise** [fiwippi/tanuki#4]
I built tanuki on my pi (arm32) and it compiled successfully after changing GOARCH to arm.

But for some reason it never loaded a folder or zip file into the library?

Am i doing something wrong or is the arm version simply weird?

```
pi@pi:~/tanuki $ unzip -l library/test.zip
Archive:  library/test.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2022-04-14 21:00   test/
   309553  2022-04-14 21:00   test/test_027.jpg
[...]
```

Even after manually reloading it via the web ui it didn't show up. Any tips?

BR

**Comment by lifeisperfecto** [comment]
Hey,

Tanuki should've made an error log in `./data/tanuki.log`, Could you post it or send it to me in some way?

I don't have an arm32 system that I can test on unfortunately. I guessing the problem might be one of two things
- The archiver package I'm using doesn't work with arm32
- The archiver package sees your `test.zip` archive as invalid for some reason

I'm travelling + have exams so I don't have too much time to debug it right now but I'll try to take a look a bit more.

**Comment by sh4nks** [comment]
I have it running on my Odroid XU4 and it works flawlessly. I did the same as you and changed the GOARCH option to ``arm``.

**Comment by OverlordAkise** [comment]
OK, i figured out how the library folder structure should be. Maybe this should be explained in the readme?

It works for things like "library/test/test.zip", but not for "library/test.zip". (You need to put archives in a folder)

Is this on purpose?

Also, if i try to do things like "library/test2/ch1/*.jpg" or "library/test1/*.jpg" it won't work and throws the following error:

`13:24:30 ERR failed to populate series db error="entries do not exist: '[test1]', entries do not exist: '[test2]'"`

Are ONLY archives supported?

Thanks for your help!

**Comment by lifeisperfecto** [comment]
> (You need to put archives in a folder), Is this on purpose?

Yeah. My idea, at least for my use case is that all archives are essentially chapters/volumes which belong to an overarching series/collection so the idea is that all relevant archives go into their relevant series folder. Would you say it's important for you to have archives which are not bound to a folder?

> Maybe this should be explained in the readme?

Good idea! I'll get to it. 

> Are ONLY archives supported?

Also, yes. Currently only archives are supported, with the supported formats being `.zip`, `.cbz`, `.rar` and `.cbr`. If you'd like more formats supported then feel free to open an issue and let me know. I'm happy to add functionality to serve images not in an archive, but again, this is something I'll only get to in the summer.

**Comment by OverlordAkise** [comment]
> Would you say it's important for you to have archives which are not bound to a folder?

For me personally: Yes, i would love such a feature. But if it's not in your "vision" for Tanuki i can completely understand that too.

Im gonna close this issue tho, cause the initial problem has been solved - thanks for your help!

**Comment by lifeisperfecto** [comment]
Cool no worries.

I'll consider adding this in the future. We'll see how it goes.
